# coding: utf-8
"""Create a program that will play the \“cows and bulls\” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a 
\“cow\”. For every digit the user guessed correctly in the wrong place is a \“bull.\” 
Every time the user makes a guess, tell them how many \“cows\” and \“bulls\” they have. 
Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  Until the user guesses the number."""
  
  
from random import randint

def cowsAndBulls():
    print "Welcome to Cows and Bulls game!"
    total_games = 0
    option = 'y'
    while (option == 'y'):
        user_input = raw_input("Enter a 4-digit number:")
        rand_number = randint(1000,9999)
        print rand_number  
        user_inputSeq = list(user_input)
        rand_seq = list(str(rand_number))
        #print user_inputSeq
        #print rand_seq
        cows = 0
        bulls = 0
        total_games += 1
        for x in range(len(user_inputSeq)):
            if (user_inputSeq[x] == rand_seq[x]):
                cows += 1
            elif (user_inputSeq[x] != rand_seq[x]):
                bulls += 1
        print "{0} cows, {1} bulls".format(cows,bulls)
        if (cows == 4 and bulls == 0):
            print "Congratulations! You win."
        option = raw_input("Do you want to play another game?(y/n):")
    print "End of Game!"
    print "Congratulations! You have played {0} games".format(total_games)

cowsAndBulls()
            
    
